name: PyInstaller
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.8-alpine
    steps:
    - uses: actions/checkout@v1

#    - name: Set up Python 3.8
#      uses: actions/setup-python@v1
#      with:
#        python-version: 3.8

    - name: Install dependencies
      run: |
        python --version
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: build with pyinstaller
      run: |
        pyinstaller --onefile --name aws_proxy main.py

    - name: run version
      run: |
        ./dist/aws_proxy --version

    - uses: actions/upload-artifact@v2
      with:
        name: aws_proxy
        path: ./dist/aws_proxy