name: New Release
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  createrelease:
    name: Create Release
    runs-on: ubuntu-latest
    container: python:3.8-alpine
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        python --version
        apk update
        apk add --no-cache postgresql-dev gcc python3-dev musl-dev libffi-dev build-base make
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    - name: build with pyinstaller
      run: |
        pyinstaller --onefile --name aws_proxy main.py
        cd dist/ && tar -czvf aws_proxy.tar.gz aws_proxy
    - name: run version
      run: |
        ./dist/aws_proxy --version

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/aws_proxy.tar.gz
        asset_name: aws_proxy_linux_alpine_amd64.tar.gz
        asset_content_type: application/tar+gzip

